In [95]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [97]:
data = pd.read_csv('../Leetcode.csv')
data.head()
data = data[['username','C++','Java','Python','Python3','C','C#','JavaScript','TypeScript','PHP','Swift','Kotlin','Dart','Go','Ruby','Scala','Rust','Racket','Erlang','Elixir','MySQL','MS SQL Server','Oracle','Pandas','PostgreSQL']]
data.head()

username  C++  Java  Python  Python3  C  C#  JavaScript  \
0     sudhanshu_090  514     1       0        0  0   0           8   
1   aryansharma1606  418    13       0        0  0   0           0   
2  mahadevwardule17  566     6       0        0  0   0           0   
3     jamshedmd1111  313     0       0        0  0   0           0   
4        Beyonder19   12   248       0        5  0   0         202   

   TypeScript  PHP  ...  Scala  Rust  Racket  Erlang  Elixir  MySQL  \
0           0    0  ...      0     0       0       0       0     57   
1           0    0  ...      0     0       0       0       0      1   
2           0    0  ...      0     0       0       0       0     16   
3           0    0  ...      0     0       0       0       0      8   
4           0    1  ...      0     0       0       0       0     39   

   MS SQL Server  Oracle  Pandas  PostgreSQL  
0              0       0       0           0  
1              0       4       0           0  
2              0       0       0           0  
3              0       0       0           0  
4              0       0       0           0  

[5 rows x 25 columns]

In [98]:
# data = df.melt(id_vars=['username'], var_name='skills', value_name='Number of question')
# 
relevant_skill_columns = data.columns[1:]

In [99]:
vectorizer = CountVectorizer()
skill_matrix = vectorizer.fit_transform(data[relevant_skill_columns])
print(skill_matrix)

  (1, 4)	1
  (2, 13)	1
  (3, 14)	1
  (6, 5)	1
  (7, 22)	1
  (8, 11)	1
  (9, 21)	1
  (10, 6)	1
  (11, 0)	1
  (12, 3)	1
  (13, 16)	1
  (14, 18)	1
  (15, 17)	1
  (16, 15)	1
  (17, 2)	1
  (18, 1)	1
  (19, 8)	1
  (20, 7)	1
  (20, 20)	1
  (20, 19)	1
  (21, 9)	1
  (22, 10)	1
  (23, 12)	1


In [100]:
similarity_matrix = cosine_similarity(skill_matrix)
print(similarity_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.

In [92]:
# Example usage











In [102]:
def recommend_skills(username, k=5):
  # Find all rows for the target user
  user_data = data[data["username"] == username]
  # print(len(user_data))

  # Handle cases where a user has only one row
  if len(user_data) == 1:
      user_index = user_data.index.values[0]
      user_skills = user_data[relevant_skill_columns].values.tolist()[0]  # Assuming skills in separate columns
  else:
      # Combine all skills from the user's rows into a set (assuming unique skills)
      user_skills = set(user_data[relevant_skill_columns].values.flatten())

  # Calculate similar users for all cases (single or multiple rows)
  print(user_index)
  user_index = user_data.index.values[0]
  print(user_index)
  similar_users = similarity_matrix[user_index].argsort()[-k:][::-1]
  print(similar_users)
  
  # Extract skills from neighbors
  neighbor_skills = data.loc[similar_users, relevant_skill_columns].values.tolist()
  neighbor_skills_flat = [item for sublist in neighbor_skills for item in sublist]  # Flatten nested list
  unique_skills = set(neighbor_skills_flat) - set(user_skills)
  
  # Filter recommended skills based on valid indices
  valid_skill_indices = range(len(vectorizer.get_feature_names_out()))  # Get valid skill indices
  filtered_unique_skills = unique_skills.intersection(valid_skill_indices)
  
  # Map recommended skill indices to skill names using CountVectorizer vocabulary
  recommended_skill_names = [vectorizer.get_feature_names_out()[idx] for idx in filtered_unique_skills]
  return recommended_skill_names
# Example usage
username = "iAmritSingh"
k = 5  # Number of recommendations

recommended_skills = recommend_skills(username, k)
print(f"Recommended skills for {username}: {recommended_skills}")

49
49


IndexError: index 49 is out of bounds for axis 0 with size 24

In [104]:
data.head(50)

username   C++  Java  Python  Python3   C  C#  JavaScript  \
0       sudhanshu_090   514     1       0        0   0   0           8   
1     aryansharma1606   418    13       0        0   0   0           0   
2    mahadevwardule17   566     6       0        0   0   0           0   
3       jamshedmd1111   313     0       0        0   0   0           0   
4          Beyonder19    12   248       0        5   0   0         202   
5          withaarzoo   530    22       3       32   0   1         138   
6           anwendeng   796     4       6      161  76   2           0   
7        Zeeshan_2512   470     0       0        3   0   0           0   
8           sgallivan   251   166      16      171   0   0        1821   
9                 uwi     1  1762       0        4   0   0           0   
10      devanshpareek   725     3       0        1   0   0           0   
11          Mandar800     0   110       0        2   0   0           0   
12        mandarmulay     0   308       0        0   0   0           0   
13          shadowfax     0   258       3        7   0   0           0   
14           Aditi_06   691     0       0        0   4   0           0   
15       aditigarg_28     5     0       2      919  14   0           0   
16       aditisingh23   481     0       0        0   0   0           0   
17             Aditi_     1   302       0        0   0   0           0   
18          Rohanfizz   889   275       0        2   0   0          30   
19        ROHANCODEIT   520     0       0        0   0   0           0   
20          Rohan1505   240     6       1       51   1   0           1   
21          rohanb459   514     1       0        0   0   0           0   
22     Kumari_Sunanda    77     0       0        0  14   0           0   
23     SunandiniM1509     5    21       0        0  13   0           0   
24         spandan611   457     1       1        1   1   0           0   
25   venkatasaitanish   677     1       0        0   0   0           0   
26              Tan_B   754     0       0      143   1   0           0   
27       tanishq_1306   460     5       0        0   0   0           3   
28         tanisha155   645     2       0        0   0   0           0   
29      taniishaajain     0     0      11      602   0   0           0   
30          tanishq1g   175     0       0        0   0   0           0   
31          Tanish_K_    53    81       0        0   0   0          15   
32     tanish27bansal   192     1       0       67   0   0           0   
33   tanishqsinghai11   775    12       0        0   0   0          14   
34  tanishsingla13390   345     7       0        2   0   0           1   
35      Harshkriplani   695     0       0        0   0   0           0   
36      HarshTekriwal     7   625       0        0  21   0           0   
37           harsh-98   107     1       0       47   0   0           0   
38    harshshah949494     0   160      18       15   0   0           0   
39     Harsh23Kashyap  1205    15       0        0   0   0           2   
40         harsh_0412  1061     1       2       26   2   0           0   
41         void_harsh   639     0       0        0   0   0           0   
42          kharsh032   687   335       1        0   0   0           0   
43             suhani     0   170      65        0   0   0           0   
44    jainmanisha3007     5     0       0        0   0   0           0   
45              129ms   323     0       0        0   0   0           0   
46         SuhaniShah     1   106       0        0   0   0           0   
47       071_Prashant   541     0       0        0   0   0           0   
48        prashant_nk  1152    23       1        0   0   0          35   
49        iAmritSingh   207     0       0        0   0   0           0   

    TypeScript  PHP  ...  Scala  Rust  Racket  Erlang  Elixir  MySQL  \
0            0    0  ...      0     0       0       0       0     57   
1            0    0  ...      0     0       0       0       0      1   
2            0    0  .

In [110]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.corpus import stopwords  # Import for stop words (optional)


def recommend_skills(data, username, k=5):
  """
  Recommends programming skills for a user based on their skills and similarity to other users.

  Args:
      data: Pandas DataFrame containing user data with username and skill columns.
      username: Username of the user for whom recommendations are needed.
      k: Number of recommendations to return (default: 5).

  Returns:
      A list of recommended skills (strings).
  """

  # Select relevant columns (username and skill columns)
  relevant_skill_columns = data.columns[1:]  # Exclude username

  # Filter rows with empty skills (optional)
  data_filtered = data[data["skills_string"].notna()]

  # Preprocess skill data (create comma-separated string)
  def filter_and_join(x):
      return ", ".join(str(val) for val in x.dropna() if isinstance(val, str))

  data_filtered["skills_string"] = data_filtered[relevant_skill_columns].apply(filter_and_join, axis=1)

  # One-hot encode skills (consider stop words handling)
  # Option 1: Disable stop word removal
  # vectorizer = CountVectorizer(stop_words=None)

  # Option 2: Customize stop words (download NLTK stopwords first)
  custom_stop_words = stopwords.words('english')
  # Add specific LeetCode terms to stop words if needed (e.g., 'Java', 'Python')
  vectorizer = CountVectorizer(stop_words=custom_stop_words)

  try:
      skill_matrix = vectorizer.fit_transform(data_filtered["skills_string"])
  except ValueError as e:
      if "empty vocabulary" in str(e):
          print("Error: Empty vocabulary encountered. Consider adjusting stop words or data preprocessing.")
          return []  # Handle empty vocabulary gracefully (no recommendations)
      else:
          raise e  # Re-raise other ValueErrors

  # Calculate user similarity
  similarity_matrix = cosine_similarity(skill_matrix)

  # Find user data
  user_data = data_filtered[data_filtered["username"] == username]

  # Handle cases with single or multiple user rows
  if len(user_data) == 1:
      user_index = user_data.index.values[0]
      user_skills = user_data["skills_string"].values[0]  # Assuming skills_string
  else:
      # Combine skills from all rows (assuming unique skills)
      user_skills = set(user_data[relevant_skill_columns].values.flatten())

  # Calculate similar users
  user_index = user_data.index.values[0]
  similar_users = similarity_matrix[user_index].argsort()[-k:][::-1]

  # Extract skills from neighbors
  neighbor_skills = data_filtered.loc[similar_users, relevant_skill_columns].values.tolist()
  neighbor_skills_flat = [item for sublist in neighbor_skills for item in sublist]  # Flatten

  # Filter recommended skills (remove user's skills)
  unique_skills = set(neighbor_skills_flat) - set(user_skills.split(", "))

  # Filter skills within vocabulary range
  valid_skills = unique_skills.intersection(set(range(len(vectorizer.get_feature_names_out()))))

  # Map recommended skill indices to skill names (using valid skills)
  recommended_skill_names = [vectorizer.get_feature_names_out()[idx] for idx in valid_skills]

  return recommended_skill_names


# Load data (replace with your CSV path)
data = pd.read_csv('../Leetcode.csv')
data.head()

# Example usage
username = "sudhanshu_090"
k = 10  # Number of recommendations

recommended_skills = recommend_skills(data.copy(), username, k)
print(f"Recommended skills for {username}: {', '.join(recommended_skills)}")


KeyError: 'skills_string'

In [133]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv('../Leetcode.csv')

data = data.drop(['total','easy','medium','hard','Array','String','Hash_Table','Math','Dynamic_Programming','Sorting','Greedy','Depth-First_Search','Binary_Search','Database','Breadth-First_Search','Tree','Matrix','Two_Pointers','Bit_Manipulation','Binary_Tree','Heap_(PriorityQueue)','Stack','PrefixSum','Simulation','Graph','Design', 'Counting', 'Sliding_Window', 'Backtracking', 'Union_Find', 'Enumeration',
    'LinkedList', 'Ordered_Set', 'Monotonic_Stack', 'Trie', 'Number_Theory',
    'Divide_and_Conquer', 'Recursion', 'Bitmask', 'Queue', 'Binary_Search_Tree',
    'Segment_Tree', 'Memoization', 'Hash_Function', 'Geometry', 'Binary_Indexed_Tree',
    'Topological_Sort', 'String_Matching', 'Combinatorics', 'Rolling_Hash',
    'Shortest_Path', 'Game_Theory', 'DataStream', 'Interactive', 'Brainteaser',
    'Monotonic_Queue', 'Randomized', 'Merge_Sort', 'Iterator', 'Concurrency',
    'Doubly-Linked List', 'Probability_and_Statistics', 'Quickselect', 'Bucket_Sort',
    'Suffix_Array', 'Minimum_Spanning_Tree', 'Counting_Sort', 'Shell', 'Line_Sweep',
    'ReservoirSampling', 'Strongly_Connected_Component', 'Eulerian_Circuit',
    'Radix_Sort', 'Rejection_Sampling', 'Biconnected_Component','rating','ranking','contestAttended','streak','totalActiveDays','OurRating','contest_LastYear','contest_6months','contest_1month','last1monthActiveDays','last6monthActiveDays'],axis=1)

print(data)

relevant_skill_columns = data.columns[1:]

# print(relevant_skill_columns)

vectorizer = CountVectorizer()
skill_matrix = vectorizer.fit_transform(data[relevant_skill_columns])


similarity_matrix = cosine_similarity(skill_matrix)




def recommend_skills(username, k=1):
  # Find all rows for the target user
  user_data = data[data["username"] == username]
  # print(len(user_data))

  # Handle cases where a user has only one row
  if len(user_data) == 1:
      user_index = user_data.index.values[0]
      user_skills = user_data[relevant_skill_columns].values.tolist()[0]  # Assuming skills in separate columns
  else:
      # Combine all skills from the user's rows into a set (assuming unique skills)
      user_skills = set(user_data[relevant_skill_columns].values.flatten())

  # Calculate similar users for all cases (single or multiple rows)
#   print(user_skills)
 
  user_index = user_data.index.values[0]
  
  
  similar_users = similarity_matrix[user_index].argsort()[-min(k, len(similarity_matrix))]  # Limit k to matrix size
  # ... (rest of the code)
  
  # Extract skills from neighbors
  neighbor_skills = data.loc[similar_users, relevant_skill_columns].values.tolist()
  neighbor_skills_flat = [item for sublist in neighbor_skills for item in sublist]  # Flatten nested list
  unique_skills = set(neighbor_skills_flat) - set(user_skills)
  
  # Filter recommended skills based on valid indices
  valid_skill_indices = range(len(vectorizer.get_feature_names_out()))  # Get valid skill indices
  filtered_unique_skills = unique_skills.intersection(valid_skill_indices)
  
  # Map recommended skill indices to skill names using CountVectorizer vocabulary
  recommended_skill_names = [vectorizer.get_feature_names_out()[idx] for idx in filtered_unique_skills]
  return recommended_skill_names

username = "sudhanshu_090"
# k = 5  # Number of recommendations

recommended_skills = recommend_skills(username, k)
print(f"Recommended skills for {username}: {recommended_skills}")

                  username  C++  Java  Python  Python3  C  C#  JavaScript  \
0            sudhanshu_090  514     1       0        0  0   0           8   
1          aryansharma1606  418    13       0        0  0   0           0   
2         mahadevwardule17  566     6       0        0  0   0           0   
3            jamshedmd1111  313     0       0        0  0   0           0   
4               Beyonder19   12   248       0        5  0   0         202   
..                     ...  ...   ...     ...      ... ..  ..         ...   
199  kulkarnimadhushree685  267     3      10       65  0   1           3   
200        pritamvkulkarni  160     0       0        0  0   0           0   
201               saketk21   79   319       0       18  0   0           1   
202                kulyash  640     0       0        5  0   0           0   
203                  manav    0   173       0        0  0   0           0   

     TypeScript  PHP  ...  Scala  Rust  Racket  Erlang  Elixir  MySQL  \
0 

TypeError: 'numpy.int64' object is not iterable